hosts:
  - username: danielg
    hostname: gerblick-ubuntu
    command:
      - /home/danielg/ros_docker/catkin_ws/src/rocket_league/docker/docker-run.sh
      - --net=host
    shutdown:
      - docker
      - stop
      - arc-rocket-league-dev
    ros_master: true
  - username: core
    hostname: citadel
    command:
      - /var/home/core/catkin_ws/src/rocket_league/docker/docker-run.sh
      - --net=host
    shutdown:
      - docker
      - stop
      - arc-rocket-league-dev
    ros_master: false