video_device: /dev/video0
image_width: 1280
image_height: 720
pixel_format: mjpeg
#io_method: userptr
camera_frame_id: gerblick_laptop
framerate: 30
#contrast: 32
#brightness: 32
#saturation: 32
#sharpness: 22
autofocus: true
#focus: 0
camera_name: gerblick_laptop

camera_matrix:
  rows: 3
  cols: 3
  data: [ 1441.948622,     0.      ,  998.400158,
             0.      ,  1443.450597,  546.123753,
             0.      ,     0.      ,    1.      ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.034722, -0.070548, -0.001782, 0.004748, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1442.588379,     0.      ,  1008.767905,    0.     ,
            0.       ,  1454.831909,  544.516360 ,    0.     ,
            0.       ,     0.      ,    1.       ,    0.     ]
