# steps to train
training_steps: 500000

reward:
  # reward to be given each frame
  constant: 0.0
  # reward as a function of squared distance from the ball
  ball_dist_sq: -5.0
  # reward as a function of squared distance from the ball to the goal
  goal_dist_sq: -10.0
  # reward given when the episode ends with the car scoring a goal
  win: 100.0

max_episode_time: 30.0

log:
  base_dir: "~/catkin_ws/data/rocketleague/"
  # frequency to save model weights. Unit is timesteps
  model_freq: 2048
  # frequency to save progress plot. Unit is episodes
  plot_freq: 25
  # variables to display in progress plot
  basic:
    - duration
  advanced:
    - goals
    - net_reward