# tuned params for no prediction at 0.15 delay
wall_avoidance:
  reverse_time: 0.125
  distance_margin: 0.375

curvature_gain: 1.5

# X coordinate to switch to defense
defensive_line: -0.5

# Y coordinate to switch to reverse
reverse_line: 0.25