# TF
FRAME_ID: "map"

# Bounding Boxes (Recorded from URDFs)
FIELD_WIDTH: 3.5 # m
FIELD_LENGTH: 5 # m
WALL_THICKNESS: 0.25 # m
GOAL_WIDTH: 1 # m
BALL_RADIUS: 0.0508 # m (2 in)
CAR_WIDTH: 0.0762 # m (3 in)
CAR_LENGTH: 0.2032 # m (8 in)

# Object Inits
CAR_INIT: {"pos": [-2.3, 0.0, 0.06], "orient": [0.0, 0.0, 1.5707963] }
BALL_INIT: [1.0, 1.0, 0.06] # Out of the way
SPEED_INIT: 0.0
