# controller type: 'lead_lag' or 'pid'
controller_type: 'lead_lag'
# parameters for all controllers
static_gain: 1.0
limits:
  min: -0.25
  max:  0.25
# parameters for lead_lag
lead:
  gain:  0.0
  alpha: 0.0
  beta:  0.0
lag:
  alpha: 0.0
  beta:  0.0
# parameters for pid
pid:
  kp: 0.0
  ki: 0.0
  kd: 0.0
  anti_windup: 0.0
  deadband: 0.0