# controller type: 'lead_lag' or 'pid'
controller_type: 'lead_lag'
# parameters for all controllers
limits:
  throttle:
    min: -1.5
    max:  1.5
# parameters for lead_lag
lead:
  gain:   0.66986
  alpha: -0.5097
  beta:  -0.9402
lag:
  alpha: -0.9802
  beta:  -0.9956
# parameters for pid
pid:
  kp: 1.0
  ki: 0.0
  kd: 0.0
  anti_windup: 0.0
  deadband: 0.0