rate: 10.0
supersampling: 10
publish_particles: true
num_particles: 1000
resample_proportion: 0.1
boundary_check: true
delay:
  compensate: true
  duration: 0.15
measurement_error:
  location: 0.05
  orientation: 0.1
generator_noise:
  location: 0.5
  orientation: 0.75
  velocity: 0.1
  steering_angle: 0.05
efforts:
  enable: true
  buffer_size: 15
  throttle:
    noise: 0.1
    max:  1.5
    min: -1.5
  steering:
    noise: 0.1
    max:  1.0
    min: -1.0