rate: 10.0
num_particles: 1000
publish_particles: true
extrapolate: true
resample_proportion: 0.1
measurement_error:
  location: 0.05
  orientation: 0.09
efforts:
  throttle:
    max:  1.5
    min: -1.5
  steering:
    max:  1.0
    min: -1.0