name: Catkin Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CMD: catkin build --no-color --workspace catkin_ws && catkin test --no-color --workspace catkin_ws
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: src
    - name: Build the local Docker image
      run: ./src/rocket_league/docker/docker-build.sh
    - name: Run `catkin build` and `catkin test` inside the Docker image
      run: ./src/rocket_league/docker/docker-run.sh
