name: docker-build-base
REPO_NAME: purduearc/rocket-league-test-repository-please-ignore:ci

on:
  push:
    branches:
      - 'ci-test'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platform: linux/amd64,linux/arm64
          tags: ${REPO_NAME}
          cache-from: type=registry,ref=${REPO_NAME}:cache
          cache-to: type=registry,ref=${REPO_NAME}:cache,mode=max
          push: false
          context: ./docker/
