name: Top level PR workflow

env:
  PR_NUMBER: ${{ github.event.number }}

on:
  pull_request:
    branches: ['main']

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.changes.outputs.docker }}
    steps:
      - name: Check for Docker updates
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            docker: ['docker/**']
      - name: Call Docker workflow
        if: steps.changes.outputs.docker == 'true'
        uses: purdue-arc/rocket_league/.github/workflows/docker-build-push.yml@main
        with:
          tag: ${{ env.PR_NUMBER }}
        secrets:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  catkin:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Call catkin workflow (tag)
        if: needs.docker.outputs.docker == 'true'
        uses: purdue-arc/rocket_league/.github/workflows/catkin-build-test.yml@main
        with:
          tag: ${{ env.PR_NUMBER }}
      - name: Call catkin workflow (latest)
        if: needs.docker.outputs.docker == 'false'
        uses: purdue-arc/rocket_league/.github/workflows/catkin-build-test.yml@main
