name: Top level PR workflow

env:
  PR_NUMBER: ${{ github.event.number }}

on:
  pull_request:
    branches: ['main']

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.changes.outputs.docker }}
    steps:
      - id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            docker: ['docker/**']
  docker:
    needs: changes
    if: needs.changes.outputs.docker == 'true'
    uses: purdue-arc/rocket_league/.github/workflows/docker-build-push.yml@ci
    with:
      tag: ${{ env.PR_NUMBER }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_PASSWORD }}
  catkin_tag:
    needs: changes, docker
    if: needs.changes.outputs.docker == 'true'
    uses: purdue-arc/rocket_league/.github/workflows/catkin-build-test.yml@main
    with:
      tag: ${{ env.PR_NUMBER }}
  catkin_latest:
    needs: changes, docker
    if: needs.changes.outputs.docker == 'false'
    uses: purdue-arc/rocket_league/.github/workflows/catkin-build-test.yml@ci