name: Top-level PR workflow

on:
  pull_request:
    branches: ['main']



jobs:
  run-black:
    name: Run black formatter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install black
        run: pip install black

      - name: Run black
        uses: wearerequired/lint-action@v1
        with:
          black: true
  changes:
    name: Check for changes to files in docker directory
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.changes.outputs.docker }}
    steps:
      - id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            docker: ['docker/**']
  docker:
    name: Rebuild Docker image and push to PR tag
    needs: changes
    if: needs.changes.outputs.docker == 'true'
    uses: purdue-arc/rocket_league/.github/workflows/docker-build-push.yml@main
    with:
      tag: ${{ github.event.number }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  catkin_tag:
    name: Catkin build and test using PR tagged Docker image
    needs: [changes, docker]
    if: needs.changes.outputs.docker == 'true'
    uses: purdue-arc/rocket_league/.github/workflows/catkin-build-test.yml@main
    with:
      tag: ${{ github.event.number }}
  catkin_latest:
    name: Catkin build and test using latest Docker image
    needs: changes
    if: needs.changes.outputs.docker == 'false'
    uses: purdue-arc/rocket_league/.github/workflows/catkin-build-test.yml@main