name: Top level PR workflow

on:
  pull_request:
    branches: ['main']

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.changes.outputs.docker }}
    steps:
      - id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            docker: ['docker/**']
  docker:
    needs: changes
    if: needs.changes.outputs.docker == 'true'
    uses: purdue-arc/rocket_league/.github/workflows/docker-build-push.yml@ci
    with:
      tag: ${{ github.event.number }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  catkin_tag:
    needs: [changes, docker]
    if: needs.changes.outputs.docker == 'true'
    uses: purdue-arc/rocket_league/.github/workflows/catkin-build-test.yml@ci
    with:
      tag: ${{ github.event.number }}
  catkin_latest:
    needs: [changes, docker]
    if: needs.changes.outputs.docker == 'false'
    uses: purdue-arc/rocket_league/.github/workflows/catkin-build-test.yml@ci